steps:
  - name: 'docker.io/kalyan0103/getting-started:v1'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "✅ Running from Docker Hub image: kalyan0103/getting-started:v1"
        # Add your custom commands here
        # Example: python3 app.py or node index.js

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cloudrun-todo'
      - '--image'
      - 'docker.io/kalyan0103/getting-started:v1'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout'
      - '300s'  # Increase timeout to 5 minutes (adjust based on app behavior)

options:
  logging: CLOUD_LOGGING_ONLY
