substitutions:
  _REGION: us-central1
  _IMAGE: us-central1-docker.pkg.dev/your-project/artifact-repo/getting-started:v1
  _SERVICE_NAME: cloudrun-todo

steps:
  # Optional test or pre-deploy step
  - name: '${_IMAGE}'
    entrypoint: sh
    args:
      - -c
      - |
        echo "✅ Running container from image: ${_IMAGE}"
        # Optional: Add test/lint/build steps here

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - --image
      - '${_IMAGE}'
      - --region
      - '${_REGION}'
      - --platform
      - managed
      - --allow-unauthenticated
      - --timeout
      - 300s

options:
  logging: CLOUD_LOGGING_ONLY
