substitutions:
  _REGION: us-central1
  _REPO: artifact-repo
  _IMAGE_NAME: getting-started
  _SERVICE_NAME: cloudrun-todo
  _PROJECT_ID: kalyan-devops-2025

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:latest'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - managed
      - '--allow-unauthenticated'
      - '--timeout'
      - 300s

options:
  logging: CLOUD_LOGGING_ONLY
